Repository hughrun/public_library_map, pull requests merged in 2021-01, with the labels that each got.

#23 Add regions
  merge_service_data.py
  website/data/boundaries.topo.json
  website/data/library_services_information.csv
  website/data/public_library_locations.csv
Labels: data

#27 Add ILS layer to map
  website/data/boundaries.topo.json
  website/data/library_services_information.csv
  website/load-map.js
Labels: data, enhancement

#35 normalise service names
  merge_service_data.py
  merge_to_topo.py
  website/data/boundaries.topo.json
  website/data/library_services_information.csv
Labels: data, plumbing

#36 add github action scripts
  .github/scripts/merge_csv_to_topojson.py
  .github/workflows/merge-csv-to-topojson.yml
  .gitignore
Labels: data, plumbing

#37 fix workflow for merging csv to topojson
  .github/workflows/merge-csv-to-topojson.yml
Labels: plumbing

#40 update docs
  about.md
  contributing.md
  website/contributing/index.html
Labels: documentation, plumbing

#45 update contributing pages
  contributing.md
  website/contributing/index.html
Labels: documentation

#46 Geo2topo
  .github/scripts/minify-map-json.sh
  .github/workflows/minify-map-json.yml
Labels: plumbing

#48 fix filepath in action
  .github/workflows/minify-map-json.yml
Labels: plumbing

#50 update github action
  .github/scripts/minify-map-json.sh
  .github/workflows/minify-map-json.yml
Labels: plumbing

#51 reconfigure minify-map-json action
  .github/scripts/minify-map-json.sh
  .github/workflows/minify-map-json.yml
Labels: plumbing

#58 Actions
  .github/workflows/merge-csv-to-topojson.yml
  .github/workflows/minify-map-json.yml
Labels: plumbing

#61 change login in Actions filter
  .github/workflows/minify-map-json.yml
Labels: plumbing

#63 update armadale libraries info
  website/data/library_services_information.csv
Labels: data

#65 PR check action
  .github/workflows/automerge.yml
Labels: plumbing

#66 whoops wrong username
  .github/workflows/automerge.yml
Labels: plumbing

#72 add albany website
  website/data/library_services_information.csv
Labels: plumbing

#74 fix rockhampton ghost library, titlecase library names, collapse excess whitespace
  website/data/public_library_locations.csv
Labels: data

#75 add bayside vic website
  website/data/library_services_information.csv
Labels: data

#76 add YPRL website
  website/data/library_services_information.csv
Labels: data

#92 Contributors
  .github/scripts/contributors.js
  .github/workflows/add-contributors.yml
  .gitignore
  README.md
  about.md
  contributors.txt
  sources.md
  website/about/index.html
  website/sources/index.html
Labels: documentation, plumbing
